const sampleData = {
    products: [
        {
            name: 'Classic Polo Shirt - White',
            slug: 'classic-polo-shirt-white',
            category: 'mens clothing',
            description: 'A stylish white polo shirt for everyday wear',
            images: [
                '/images/sample-products/t1.jpg',
                '/images/sample-products/t2.jpg',
            ],
            price: 29.99,
            brand: 'polo',
            rating: 4.5,
            numReviews: 10,
            stock: 20,
            isFeatured: true,
            banner: '/images/sample-products/ng.jpg',
        },
        {
            name: 'Premium Polo Shirt - Black',
            slug: 'premium-polo-shirt-black',
            category: 'mens clothing',
            description: 'A stylish black polo shirt for special occasions',
            images: [
                '/images/sample-products/t8.jpg',
            ],
            price: 34.99,
            brand: 'polo',
            rating: 4.5,
            numReviews: 15,
            stock: 0,
            isFeatured: true,
            banner: '/images/sample-products/ng.jpg',
        },
        {
            name: 'Sport Polo Shirt - Navy',
            slug: 'sport-polo-shirt-navy',
            category: 'mens clothing',
            description: 'A stylish navy polo shirt for active lifestyle',
            images: [
                '/images/sample-products/t3.jpg',
                '/images/sample-products/t2.jpg',
            ],
            price: 32.99,
            brand: 'polo',
            rating: 4.3,
            numReviews: 8,
            stock: 20,
            isFeatured: true,
            banner: '/images/sample-products/ng.jpg',
        },
        {
            name: 'Casual Polo Shirt - Gray',
            slug: 'casual-polo-shirt-gray',
            category: 'mens clothing',
            description: 'A stylish gray polo shirt for casual outings',
            images: [
                '/images/sample-products/t4.jpg',
                '/images/sample-products/t2.jpg',
            ],
            price: 28.99,
            brand: 'polo',
            rating: 4.2,
            numReviews: 12,
            stock: 20,
            isFeatured: false,
            banner: '/images/sample-products/ng.jpg',
        },
        {
            name: 'Business Polo Shirt - Blue',
            slug: 'business-polo-shirt-blue',
            category: 'mens clothing',
            description: 'A stylish blue polo shirt for business casual',
            images: [
                '/images/sample-products/t5.jpg',
                '/images/sample-products/t2.jpg',
            ],
            price: 35.99,
            brand: 'polo',
            rating: 4.6,
            numReviews: 18,
            stock: 20,
            isFeatured: true,
            banner: '/images/sample-products/ng.jpg',
        },
        {
            name: 'Vintage Polo Shirt - Green',
            slug: 'vintage-polo-shirt-green',
            category: 'mens clothing',
            description: 'A stylish green polo shirt with vintage appeal',
            images: [
                '/images/sample-products/t6.jpg',
                '/images/sample-products/t2.jpg',
            ],
            price: 31.99,
            brand: 'polo',
            rating: 4.4,
            numReviews: 9,
            stock: 20,
            isFeatured: false,
            banner: '/images/sample-products/ng.jpg',
        },
        {
            name: 'Summer Polo Shirt - Yellow',
            slug: 'summer-polo-shirt-yellow',
            category: 'mens clothing',
            description: 'A stylish yellow polo shirt perfect for summer',
            images: [
                '/images/sample-products/t7.jpg',
                '/images/sample-products/t2.jpg',
            ],
            price: 27.99,
            brand: 'polo',
            rating: 4.1,
            numReviews: 7,
            stock: 20,
            isFeatured: false,
            banner: '/images/sample-products/ng.jpg',
        },
        {
            name: 'Athletic Polo Shirt - Red',
            slug: 'athletic-polo-shirt-red',
            category: 'mens clothing',
            description: 'A stylish red polo shirt for athletic activities',
            images: [
                '/images/sample-products/t8.jpg',
                '/images/sample-products/t2.jpg',
            ],
            price: 33.99,
            brand: 'polo',
            rating: 4.5,
            numReviews: 14,
            stock: 20,
            isFeatured: true,
            banner: '/images/sample-products/ng.jpg',
        },
        {
            name: 'Luxury Polo Shirt - Purple',
            slug: 'luxury-polo-shirt-purple',
            category: 'mens clothing',
            description: 'A stylish purple polo shirt with luxury feel',
            images: [
                '/images/sample-products/t9.jpg',
                '/images/sample-products/t2.jpg',
            ],
            price: 39.99,
            brand: 'polo',
            rating: 4.7,
            numReviews: 22,
            stock: 20,
            isFeatured: true,
            banner: '/images/sample-products/ng.jpg',
        },
        {
            name: 'Weekend Polo Shirt - Orange',
            slug: 'weekend-polo-shirt-orange',
            category: 'mens clothing',
            description: 'A stylish orange polo shirt for weekend relaxation',
            images: [
                '/images/sample-products/t10.jpg',
                '/images/sample-products/t2.jpg',
            ],
            price: 26.99,
            brand: 'polo',
            rating: 4.0,
            numReviews: 6,
            stock: 20,
            isFeatured: false,
            banner: '/images/sample-products/ng.jpg',
        },
    ]
}

export default sampleData;